### ISSUE TITLE
【一般】管理门户》资源管理》机房信息添加/修改，机房编号校验不正确

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#1]
1. 管理门户》资源管理》机房信息添加/修改页面，机房编号 说明为“ 1-40位数字字母下划线的组合”，但“room-2”这种形式可提交成功
2. 数据中心代码，资源中心代码，网络区域代码，服务器编号的添加/修改页面也有此问题

**Comment by wanwb** [comment]
已修改

**Comment by yuanhj3** [comment]
已修改提示为：数字字母下划线或中线的组合
