### ISSUE TITLE
【一般】管理门户》资源管理，平台资源被使用的情况下，设置资源（机房、数据中心、资源中心、网络区域、服务器）失效时，应给出提示

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#11]
管理门户》资源管理，平台资源被使用的情况下，设置资源（机房、数据中心、资源中心、网络区域、服务器）失效时，应给出提示

**Comment by wanwb** [comment]
设为无效对之前用到了的资源不会有影响，对后续使用的就选不到了，这里的无效主要作用也是说后续的业务选不到，用户体验上提示是要好些，但每个地方需要加提示会有一定工作量，比较繁多，而且实际设无效的可能性也不大
