### ISSUE TITLE
【一般】管理门户》镜像管理》镜像库管理，删除已被使用的镜像库，应给出提示。

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#15]
管理门户》镜像管理》镜像库管理，删除已被使用的镜像库，应给出提示。

**Comment by chen-xm** [comment]
1）、提测的功能说明：已经使用的镜像库不能删除，已修复
	2）、代码分支说明： PaaS-BE-Platform-MGMT / develop
	3）、配置信息说明：无
	4）、数据库说明：无
	5）、是否有特殊的第三方软件安装：无
