### ISSUE TITLE
【一般】管理门户》资源管理，修改机房信息，提交时，不能成功提交，提示“机房编号已存在!”，数据中心、资源中心、网络区域、服务器登记也有此问题

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#17]
管理门户》资源管理，修改机房信息，提交时，不能成功提交，提示“机房编号已存在!”，数据中心、资源中心、网络区域、服务器登记也有此问题

**Comment by yuanhj3** [comment]
修改镜像库信息，提交时，也有此问题

**Comment by chen-xm** [comment]
1）、提测的功能说明：编码相同时，不能修改问题已修复。新添加时提示”编号已存在“
	2）、代码分支说明： PaaS-BE-Platform-MGMT / develop
	3）、配置信息说明：无
	4）、数据库说明：无
	5）、是否有特殊的第三方软件安装：无
