### ISSUE TITLE
【一般】登录-资源管理-资源中心部署-列表中，标签 字段，应为 是否有效

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-BE-Platform-MGMT#21]
环境：win7
浏览器：火狐
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.进入 资源管理-资源中心部署-列表中，标签 字段
实际结果：
书写错误 
 预期结果：
应为 是否有效

**Comment by yuanman001** [comment]
袁会娟已经提了这个bug了，已经调整了

**Comment by chen-xm** [comment]
已修改

**Comment by chen-xm** [comment]
1）、提测的功能说明：列表已经调整
2）、代码分支说明： PaaS-BE-Platform-MGMT / develop
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无

**Comment by chenhy6** [comment]
验证通过
