### ISSUE TITLE
[一般]（管理门户）登录-资源管理-资源中心部署-查询，缺少“查询”按钮

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-BE-Platform-MGMT#22]
环境：win7
浏览器：火狐
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.进入资源管理-资源中心部署-查询
实际结果：
没有“查询”按钮
预期结果：
需要添加“查询”按钮

**Comment by chen-xm** [comment]
1）、提测的功能说明：已添加查询按钮
2）、代码分支说明： PaaS-BE-Platform-MGMT / develop
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无

**Comment by chenhy6** [comment]
验证通过
