### ISSUE TITLE
【一般】（管理门户）登录-资源管理-资源中心部署-查询-下拉列表框中，选择“全部”，资源中心部署列表无数据显示

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-BE-Platform-MGMT#23]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.进入资源管理-资源中心部署-查询-下拉列表框中，选择“全部”
实际结果：
资源中心部署列表无数据显示
预期结果：
显示所有数据信息

**Comment by chen-xm** [comment]
1）、提测的功能说明：已删除全部下拉框，此页面无全部查询
2）、代码分支说明： PaaS-BE-Platform-MGMT / develop
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无

**Comment by chenhy6** [comment]
验证通过
