### ISSUE TITLE
【一般】（管理门户）登录-资源管理-资源中心部署-列表-标签详情，不起作用

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-BE-Platform-MGMT#24]
环境：win7
浏览器：火狐
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.进入资源管理-资源中心部署-列表-标签详情
实际结果：
点击”标签详情“按钮不起作用
 预期结果：
正确显示详情内容

**Comment by chen-xm** [comment]
1）、提测的功能说明：已删除该标签，调整列表
	2）、代码分支说明： PaaS-BE-Platform-MGMT / develop
	3）、配置信息说明：无
	4）、数据库说明：无
	5）、是否有特殊的第三方软件安装：无
