### ISSUE TITLE
【一般】管理门户》资源管理》服务器登记，添加服务器信息时，登录帐号和登录密码应当为必填项。

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#25]
管理门户》资源管理》服务器登记，添加服务器信息时，登录帐号和登录密码应当为必填项。

**Comment by chen-xm** [comment]
1）、提测的功能说明：已修改服务器账号和密码为必填
	2）、代码分支说明： PaaS-BE-Platform-MGMT / develop
	3）、配置信息说明：无
	4）、数据库说明：无
	5）、是否有特殊的第三方软件安装：无
