### ISSUE TITLE
【一般】（管理门户）登录-资源管理-资源中心部署-资源中心注销成功后，缺少 自动刷新返回初始化页面的功能

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-BE-Platform-MGMT#30]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.进入 资源管理-资源中心部署-资源中心注销成功后，
实际结果：
停留在原来的页面
预期结果：
自动刷新返回初始化页面

**Comment by chen-xm** [comment]
已修改

**Comment by chen-xm** [comment]
已修改

**Comment by chenhy6** [comment]
验证通过
