### ISSUE TITLE
【一般】管理门户》资源管理》资源中心登记，添加或修改资源中心信息时，镜像库和镜像库地址可以填写不同镜像库的信息，请修改。

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#32]
管理门户》资源管理》资源中心登记，添加或修改资源中心信息时，镜像库和镜像库地址可以填写不同镜像库的信息，请修改。

**Comment by yuanman001** [comment]
两处的镜像地址不是一个概念，已将资源中心登记中的镜像地址，修改为“镜像存储路径”，并增加了相关的描述。
