### ISSUE TITLE
【一般】管理门户、用户门户，所有查询页面没有正确的排序

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#5]
管理门户、用户门户，所有查询页面没有正确的排序

应该按照什么方式排序，可以和设计人员一起商定

**Comment by wanwb** [comment]
我们目前的排序原则是：有代码字段的按代码字段顺序排序，没有代码字段的按创建时间顺序排序

**Comment by yuanhj3** [comment]
那所有的排序请按照，创建时间的倒序  排列
