### ISSUE TITLE
【一般】页面展示或者点击按钮，浏览器不兼容，需要支持谷歌、IE、360、火狐。

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#6]
页面展示或者点击按钮，浏览器不兼容，需要支持谷歌、IE、360、火狐。

**Comment by wanwb** [comment]
请指出具体的页面?

**Comment by yuanhj3** [comment]
管理门户》资源管理》资源中心页面： chrome中，查询和添加按钮分行显示
用户门户，登录界面：chrome中，注册申请链接，分行显示
管理门户》系统管理》后台权限》系统用户：chrome中，点击具体用户编号链接，打不开用户详细信息页面
管理门户》系统管理》后台权限》系统角色：chrome中，打不开角色代码所链接的页面
管理门户》系统管理》前台权限》前台角色：chrome中，打不开角色代码所链接的页面

**Comment by wanwb** [comment]
<管理门户》资源管理》资源中心页面： chrome中，查询和添加按钮分行显示
用户门户，登录界面：chrome中，注册申请链接，分行显示>
这已修改

系统管理中问题目前只支持IE

**Comment by yuanhj3** [comment]
经讨论，谷歌、IE9以上、360、火狐这几种觉的浏览器都要支持，请修改

**Comment by wanwb** [comment]
已修改，请重新部署paas-csys工程进行验证

**Comment by zhangft** [comment]
基础管理模块的 系统代码里面的添加、查看还是无法正常使用。

 
发件人： wanwb
发送时间： 2016-03-19 14:08
收件人： AIPaaS/PaaS-BE-Platform-MGMT
抄送： zhangft
主题： Re: [PaaS-BE-Platform-MGMT] 【一般】页面展示或者点击按钮，浏览器不兼容，需要支持谷歌、IE、360、火狐。 (#6)
已修改，请重新部署paas-csys工程进行验证

**Comment by wanwb** [comment]
已修改
