### ISSUE TITLE
【一般】管理门户》资源管理》机房信息添加/修改，联系电话、邮件格式校验不正确

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/PaaS-BE-Platform-MGMT#7]
管理门户》资源管理》机房信息添加/修改
1、机房联系电话格式无校验，字母、特殊字符、负数都可成功提交；
2、机房联系邮箱格式校验不正确，“example@11”也可成功提交

**Comment by guohong1** [comment]
已修改

**Comment by yuanhj3** [comment]
机房联系邮箱格式校验不成功，11@11这种形式的也可成功提交
机房联系电话格式校验不成功，18510862602这种形式不能成功提交，提示为“请与所要求格式保持一致”

**Comment by chen-xm** [comment]
已修改

**Comment by chen-xm** [comment]
1）、提测的功能说明：已添加联系电话、邮件格式校验
	2）、代码分支说明：develop
	3）、配置信息说明：无
	4）、数据库说明：无
	5）、是否有特殊的第三方软件安装：无
